{{- if .Values.traefik.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: {{ .Release.Namespace }}
  labels:
    rollme: {{ template "rollMe" . }}
spec:
  parentRefs:
  - name: {{ .Values.traefik.gateway.name }}
    sectionName: websecure
    namespace: {{ .Release.Namespace }}
  hostnames:
  - {{ .Values.host }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: backend
      port: {{ .Values.federatedNode.port }}
{{- end -}}
