apiVersion: batch/v1
kind: Job
metadata:
  name: dagster-postgres-init
  namespace: fn
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: postgres:14
          env:
            - name: PGHOST
              value: db.fn.svc
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: admin
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: local-db
                  key: password
          command:
            - sh
            - -c
            - |
              set -e

              echo "Ensuring dagster database exists..."

              EXISTS=$(psql -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='dagster'")

              if [ "$EXISTS" != "1" ]; then
                echo "Creating dagster database"
                psql -d postgres -c "CREATE DATABASE dagster"
              else
                echo "Dagster database already exists"
              fi

              echo "Done."
