apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-artifacts-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "storageClassName" . }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.storage.local.artifacts }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fn-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  namespace: {{ .Release.namespace }}
spec:
  storageClassName: {{ include "storageClassName" . }}
  volumeName: dagster-artifacts-pv
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteMany

