{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-minio-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  # storageClassName: {{ include "storageClassName" . }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.storage.local.minio }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fn-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: dagster-minio-pv
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
{{- end }}
