# {{- if .Values.traefik.enabled -}}
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: {{ include "gatewayName" . }}-class
# spec:
#   controllerName: "traefik.io/gateway-controller"
# {{- end -}}
# # kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
