apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-postgres-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/dagster/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fn-control-plane
