apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-rabbitmq-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "storageClassName" . }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.storage.local.rabbit }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fn-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvc
spec:
  storageClassName: {{ include "storageClassName" . }}
  volumeName: dagster-rabbitmq-pv
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteMany

