kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30001
    protocol: TCP
  extraMounts:
  - hostPath: /phems/data
    containerPath: /phems/data
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime.options]
      mtu = 1200
